// Code generated by oidgen from oids.json; DO NOT EDIT.

/// Version of the Privasys OID scheme these constants implement.
pub const OID_SCHEME_VERSION: u32 = 2;

/// SGX Quote. Intel arc. A v1 certificate extension; in v2 the quote travels in the attest response and a leaf that carries it is a v1 leaf (rejected).
pub const OID_SGX_QUOTE: &str = "1.2.840.113741.1.13.1.0";
/// TDX Quote. Intel arc. Same status as SGX_QUOTE.
pub const OID_TDX_QUOTE: &str = "1.2.840.113741.1.5.5.1.6";

// Arc 1, Platform identity: What runs here, which instance.
/// Runtime Version Hash (1.3.6.1.4.1.65230.1.1): 32 bytes, SHA-256 of the runtime version (Wasmtime on Mini, containerd on Virtual).
pub const OID_RUNTIME_VERSION_HASH: &str = "1.3.6.1.4.1.65230.1.1";
/// Image Profile (1.3.6.1.4.1.65230.1.2): UTF-8 string, "production" or "dev".
pub const OID_IMAGE_PROFILE: &str = "1.3.6.1.4.1.65230.1.2";
/// Enclave Instance ID (1.3.6.1.4.1.65230.1.3): 16-byte UUID, the management-service enclave_id received at registration.
pub const OID_ENCLAVE_INSTANCE_ID: &str = "1.3.6.1.4.1.65230.1.3";
/// Platform Hardware Identity (1.3.6.1.4.1.65230.1.4): reserved for Platform Ownership Endorsements. Reserved, never emitted.
pub const OID_PLATFORM_HARDWARE_IDENTITY: &str = "1.3.6.1.4.1.65230.1.4";

// Arc 2, Platform configuration: Operator-chosen inputs of the platform.
/// Config Merkle Root (1.3.6.1.4.1.65230.2.1): 32 bytes, root over every configuration input of the platform.
pub const OID_CONFIG_MERKLE_ROOT: &str = "1.3.6.1.4.1.65230.2.1";
/// Egress CA Bundle Hash (1.3.6.1.4.1.65230.2.2): 32 bytes, SHA-256 of the outbound trust-anchor bundle.
pub const OID_EGRESS_CA_HASH: &str = "1.3.6.1.4.1.65230.2.2";
/// Attestation Servers Hash (1.3.6.1.4.1.65230.2.3): 32 bytes, SHA-256 of the sorted attestation server URL list.
pub const OID_ATTESTATION_SERVERS_HASH: &str = "1.3.6.1.4.1.65230.2.3";
/// Combined Workloads Hash (1.3.6.1.4.1.65230.2.4): 32 bytes, SHA-256 over the loaded workload set.
pub const OID_COMBINED_WORKLOADS_HASH: &str = "1.3.6.1.4.1.65230.2.4";

// Arc 3, Platform keys and state: Key origin and authenticated state of the platform.
/// Data Encryption Key Origin (1.3.6.1.4.1.65230.3.1): UTF-8 string, "byok:<fingerprint>" or "generated".
pub const OID_DEK_ORIGIN: &str = "1.3.6.1.4.1.65230.3.1";
/// Authenticated State Root (1.3.6.1.4.1.65230.3.2): 40 bytes, 32-byte Merkle root followed by a big-endian u64 version.
pub const OID_AUTHENTICATED_STATE_ROOT: &str = "1.3.6.1.4.1.65230.3.2";

// Arc 4, Workload identity: Which app, which code.
/// Workload App ID (1.3.6.1.4.1.65230.4.1): 16-byte UUID, the management app id.
pub const OID_WORKLOAD_APP_ID: &str = "1.3.6.1.4.1.65230.4.1";
/// Workload Code Digest (1.3.6.1.4.1.65230.4.2): 32 bytes, SHA-256 of the WASM bytecode (Mini) or of the OCI manifest (Virtual).
pub const OID_WORKLOAD_CODE_HASH: &str = "1.3.6.1.4.1.65230.4.2";
/// Workload Image Ref (1.3.6.1.4.1.65230.4.3): UTF-8 string, image reference without digest.
pub const OID_WORKLOAD_IMAGE_REF: &str = "1.3.6.1.4.1.65230.4.3";

// Arc 5, Workload configuration: Configuration of one workload, including the app-defined sub-arc.
/// Workload Config Merkle Root (1.3.6.1.4.1.65230.5.1): 32 bytes.
pub const OID_WORKLOAD_CONFIG_MERKLE_ROOT: &str = "1.3.6.1.4.1.65230.5.1";
/// Workload Configuration Hash (1.3.6.1.4.1.65230.5.2): 32 bytes, runtime-stamped hash of the workload configuration.
pub const OID_WORKLOAD_CONFIGURATION_HASH: &str = "1.3.6.1.4.1.65230.5.2";
/// Reserved (1.3.6.1.4.1.65230.5.3): reserved. Reserved, never emitted.
pub const OID_WORKLOAD_RESERVED_5_3: &str = "1.3.6.1.4.1.65230.5.3";
/// Model Digest (1.3.6.1.4.1.65230.5.4.5): app-defined (SDK set-attestation-extension), 32 bytes.
pub const OID_WORKLOAD_MODEL_DIGEST: &str = "1.3.6.1.4.1.65230.5.4.5";
/// Tools Digest (1.3.6.1.4.1.65230.5.4.7): app-defined (SDK set-attestation-extension), 32 bytes.
pub const OID_WORKLOAD_TOOLS_DIGEST: &str = "1.3.6.1.4.1.65230.5.4.7";

// Arc 6, Workload keys and state: Key source and authenticated state of one workload.
/// Workload Key Source (1.3.6.1.4.1.65230.6.1): UTF-8 string, "byok:<fingerprint>", "generated" or "vault:<path>".
pub const OID_WORKLOAD_KEY_SOURCE: &str = "1.3.6.1.4.1.65230.6.1";
/// Workload State Root (1.3.6.1.4.1.65230.6.2): reserved, mirrors 3.2 for per-workload authenticated stores. Reserved, never emitted.
pub const OID_WORKLOAD_STATE_ROOT: &str = "1.3.6.1.4.1.65230.6.2";

// Arc 7, Trust relationships: Pinned relationships between enclaves.
/// Attested Dependency Set (1.3.6.1.4.1.65230.7.1): canonical dependency-set encoding (EncodeDependencySet), written by the runtime.
pub const OID_ATTESTED_DEPENDENCY_SET: &str = "1.3.6.1.4.1.65230.7.1";
/// Allowed Callers (1.3.6.1.4.1.65230.7.2): reserved, enforced from the management database today. Reserved, never emitted.
pub const OID_ALLOWED_CALLERS: &str = "1.3.6.1.4.1.65230.7.2";

/// The whole Privasys private-enterprise arc, with a trailing dot. Membership in CertInfo.CustomOids is by arc, not by allowlist.
pub const OID_PRIVASYS_ARC_PREFIX: &str = "1.3.6.1.4.1.65230.";
/// Sub-arc apps publish attested digests under, through the SDK set-attestation-extension call. Open-ended by design; the root 5.4 never carries a value.
pub const OID_APP_EXTENSION_ARC_PREFIX: &str = "1.3.6.1.4.1.65230.5.4.";

// Arc 8, evidence types: identifiers for the evidence bodies of the post-handshake
// attest response. Never certificate extensions.
/// Intel SGX DCAP quote (tee "sgx").
pub const OID_EVIDENCE_SGX_QUOTE: &str = "1.3.6.1.4.1.65230.8.1";
/// Intel TDX DCAP quote (tee "tdx").
pub const OID_EVIDENCE_TDX_QUOTE: &str = "1.3.6.1.4.1.65230.8.2";
/// AMD SEV-SNP report (tee "sev-snp").
pub const OID_EVIDENCE_SEV_SNP_REPORT: &str = "1.3.6.1.4.1.65230.8.3";
/// NVIDIA GPU CC evidence (tee "nvidia-gpu").
pub const OID_EVIDENCE_NVIDIA_GPU: &str = "1.3.6.1.4.1.65230.8.4";

/// One extension of the scheme.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct OidEntry {
    pub oid: &'static str,
    pub name: &'static str,
    pub label: &'static str,
    pub category: &'static str,
    pub reserved: bool,
    pub app_defined: bool,
}

/// Every extension of the scheme with its label.
pub const ALL_OIDS: &[OidEntry] = &[
    OidEntry { oid: OID_RUNTIME_VERSION_HASH, name: "RUNTIME_VERSION_HASH", label: "Runtime Version Hash", category: "platform-identity", reserved: false, app_defined: false },
    OidEntry { oid: OID_IMAGE_PROFILE, name: "IMAGE_PROFILE", label: "Image Profile", category: "platform-identity", reserved: false, app_defined: false },
    OidEntry { oid: OID_ENCLAVE_INSTANCE_ID, name: "ENCLAVE_INSTANCE_ID", label: "Enclave Instance ID", category: "platform-identity", reserved: false, app_defined: false },
    OidEntry { oid: OID_PLATFORM_HARDWARE_IDENTITY, name: "PLATFORM_HARDWARE_IDENTITY", label: "Platform Hardware Identity", category: "platform-identity", reserved: true, app_defined: false },
    OidEntry { oid: OID_CONFIG_MERKLE_ROOT, name: "CONFIG_MERKLE_ROOT", label: "Config Merkle Root", category: "platform-configuration", reserved: false, app_defined: false },
    OidEntry { oid: OID_EGRESS_CA_HASH, name: "EGRESS_CA_HASH", label: "Egress CA Bundle Hash", category: "platform-configuration", reserved: false, app_defined: false },
    OidEntry { oid: OID_ATTESTATION_SERVERS_HASH, name: "ATTESTATION_SERVERS_HASH", label: "Attestation Servers Hash", category: "platform-configuration", reserved: false, app_defined: false },
    OidEntry { oid: OID_COMBINED_WORKLOADS_HASH, name: "COMBINED_WORKLOADS_HASH", label: "Combined Workloads Hash", category: "platform-configuration", reserved: false, app_defined: false },
    OidEntry { oid: OID_DEK_ORIGIN, name: "DEK_ORIGIN", label: "Data Encryption Key Origin", category: "platform-keys-state", reserved: false, app_defined: false },
    OidEntry { oid: OID_AUTHENTICATED_STATE_ROOT, name: "AUTHENTICATED_STATE_ROOT", label: "Authenticated State Root", category: "platform-keys-state", reserved: false, app_defined: false },
    OidEntry { oid: OID_WORKLOAD_APP_ID, name: "WORKLOAD_APP_ID", label: "Workload App ID", category: "workload-identity", reserved: false, app_defined: false },
    OidEntry { oid: OID_WORKLOAD_CODE_HASH, name: "WORKLOAD_CODE_HASH", label: "Workload Code Digest", category: "workload-identity", reserved: false, app_defined: false },
    OidEntry { oid: OID_WORKLOAD_IMAGE_REF, name: "WORKLOAD_IMAGE_REF", label: "Workload Image Ref", category: "workload-identity", reserved: false, app_defined: false },
    OidEntry { oid: OID_WORKLOAD_CONFIG_MERKLE_ROOT, name: "WORKLOAD_CONFIG_MERKLE_ROOT", label: "Workload Config Merkle Root", category: "workload-configuration", reserved: false, app_defined: false },
    OidEntry { oid: OID_WORKLOAD_CONFIGURATION_HASH, name: "WORKLOAD_CONFIGURATION_HASH", label: "Workload Configuration Hash", category: "workload-configuration", reserved: false, app_defined: false },
    OidEntry { oid: OID_WORKLOAD_RESERVED_5_3, name: "WORKLOAD_RESERVED_5_3", label: "Reserved", category: "workload-configuration", reserved: true, app_defined: false },
    OidEntry { oid: OID_WORKLOAD_MODEL_DIGEST, name: "WORKLOAD_MODEL_DIGEST", label: "Model Digest", category: "workload-configuration", reserved: false, app_defined: true },
    OidEntry { oid: OID_WORKLOAD_TOOLS_DIGEST, name: "WORKLOAD_TOOLS_DIGEST", label: "Tools Digest", category: "workload-configuration", reserved: false, app_defined: true },
    OidEntry { oid: OID_WORKLOAD_KEY_SOURCE, name: "WORKLOAD_KEY_SOURCE", label: "Workload Key Source", category: "workload-keys-state", reserved: false, app_defined: false },
    OidEntry { oid: OID_WORKLOAD_STATE_ROOT, name: "WORKLOAD_STATE_ROOT", label: "Workload State Root", category: "workload-keys-state", reserved: true, app_defined: false },
    OidEntry { oid: OID_ATTESTED_DEPENDENCY_SET, name: "ATTESTED_DEPENDENCY_SET", label: "Attested Dependency Set", category: "trust", reserved: false, app_defined: false },
    OidEntry { oid: OID_ALLOWED_CALLERS, name: "ALLOWED_CALLERS", label: "Allowed Callers", category: "trust", reserved: true, app_defined: false },
];

/// Human-readable label for a known OID, or "Unknown".
pub fn oid_label(oid: &str) -> String {
    match oid {
        "1.2.840.113741.1.13.1.0" => "SGX Quote".to_string(),
        "1.2.840.113741.1.5.5.1.6" => "TDX Quote".to_string(),
        "1.3.6.1.4.1.65230.1.1" => "Runtime Version Hash".to_string(),
        "1.3.6.1.4.1.65230.1.2" => "Image Profile".to_string(),
        "1.3.6.1.4.1.65230.1.3" => "Enclave Instance ID".to_string(),
        "1.3.6.1.4.1.65230.1.4" => "Platform Hardware Identity".to_string(),
        "1.3.6.1.4.1.65230.2.1" => "Config Merkle Root".to_string(),
        "1.3.6.1.4.1.65230.2.2" => "Egress CA Bundle Hash".to_string(),
        "1.3.6.1.4.1.65230.2.3" => "Attestation Servers Hash".to_string(),
        "1.3.6.1.4.1.65230.2.4" => "Combined Workloads Hash".to_string(),
        "1.3.6.1.4.1.65230.3.1" => "Data Encryption Key Origin".to_string(),
        "1.3.6.1.4.1.65230.3.2" => "Authenticated State Root".to_string(),
        "1.3.6.1.4.1.65230.4.1" => "Workload App ID".to_string(),
        "1.3.6.1.4.1.65230.4.2" => "Workload Code Digest".to_string(),
        "1.3.6.1.4.1.65230.4.3" => "Workload Image Ref".to_string(),
        "1.3.6.1.4.1.65230.5.1" => "Workload Config Merkle Root".to_string(),
        "1.3.6.1.4.1.65230.5.2" => "Workload Configuration Hash".to_string(),
        "1.3.6.1.4.1.65230.5.3" => "Reserved".to_string(),
        "1.3.6.1.4.1.65230.5.4.5" => "Model Digest".to_string(),
        "1.3.6.1.4.1.65230.5.4.7" => "Tools Digest".to_string(),
        "1.3.6.1.4.1.65230.6.1" => "Workload Key Source".to_string(),
        "1.3.6.1.4.1.65230.6.2" => "Workload State Root".to_string(),
        "1.3.6.1.4.1.65230.7.1" => "Attested Dependency Set".to_string(),
        "1.3.6.1.4.1.65230.7.2" => "Allowed Callers".to_string(),
        "1.3.6.1.4.1.65230.8.1" => "Intel SGX DCAP quote".to_string(),
        "1.3.6.1.4.1.65230.8.2" => "Intel TDX DCAP quote".to_string(),
        "1.3.6.1.4.1.65230.8.3" => "AMD SEV-SNP report".to_string(),
        "1.3.6.1.4.1.65230.8.4" => "NVIDIA GPU CC evidence".to_string(),
        _ => {
            if let Some(rest) = oid.strip_prefix(OID_APP_EXTENSION_ARC_PREFIX) {
                if !rest.is_empty() {
                    return format!("App-defined extension {}", rest);
                }
            }
            "Unknown".to_string()
        }
    }
}
