// Copyright (c) Privasys. All rights reserved.
// Licensed under the GNU Affero General Public License v3.0. See LICENSE file for details.

// oidgen renders the Privasys OID scheme (oids.json at the repository root)
// into the constant tables of every SDK and into docs/oids.md.
//
//	cd go && go run ./cmd/oidgen -root ..          # write
//	cd go && go run ./cmd/oidgen -root .. -check   # CI: fail when a generated file is stale
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type quoteExt struct {
	Name  string `json:"name"`
	OID   string `json:"oid"`
	Label string `json:"label"`
	Note  string `json:"note"`
}

type arc struct {
	Number      int    `json:"number"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type extension struct {
	Name       string  `json:"name"`
	Suffix     string  `json:"suffix"`
	Label      string  `json:"label"`
	Category   string  `json:"category"`
	Encoding   string  `json:"encoding"`
	Mini       bool    `json:"mini"`
	Virtual    bool    `json:"virtual"`
	Reserved   bool    `json:"reserved"`
	AppDefined bool    `json:"app_defined"`
	V1         *string `json:"v1"`
}

type prefix struct {
	Name        string `json:"name"`
	Suffix      string `json:"suffix"`
	Label       string `json:"label"`
	Description string `json:"description"`
}

type evidenceType struct {
	Name   string `json:"name"`
	Suffix string `json:"suffix"`
	Label  string `json:"label"`
	Tee    string `json:"tee"`
	V1     string `json:"v1"`
}

type retired struct {
	V1   string `json:"v1"`
	Was  string `json:"was"`
	Note string `json:"note"`
}

type scheme struct {
	Arc           string         `json:"arc"`
	SchemeVersion int            `json:"scheme_version"`
	Quotes        []quoteExt     `json:"quote_extensions"`
	Arcs          []arc          `json:"arcs"`
	Extensions    []extension    `json:"extensions"`
	Prefixes      []prefix       `json:"prefixes"`
	Evidence      []evidenceType `json:"evidence_types"`
	Retired       []retired      `json:"retired"`
}

func (s *scheme) oid(suffix string) string {
	if suffix == "" {
		return s.Arc + "."
	}
	if strings.HasSuffix(suffix, ".") {
		return s.Arc + "." + suffix
	}
	return s.Arc + "." + suffix
}

var acronyms = map[string]bool{"ID": true, "CA": true, "DEK": true, "SGX": true, "TDX": true, "SEV": true, "SNP": true, "NVIDIA": true, "GPU": true}

// camel turns RUNTIME_VERSION_HASH into RuntimeVersionHash, keeping acronyms
// (WORKLOAD_APP_ID -> WorkloadAppID, EGRESS_CA_HASH -> EgressCAHash).
func camel(name string) string {
	var b strings.Builder
	for _, part := range strings.Split(name, "_") {
		if part == "" {
			continue
		}
		if acronyms[part] {
			b.WriteString(part)
			continue
		}
		b.WriteString(strings.ToUpper(part[:1]))
		b.WriteString(strings.ToLower(part[1:]))
	}
	return b.String()
}

const header = "Code generated by oidgen from oids.json; DO NOT EDIT."

type labelled struct{ oid, label string }

func (s *scheme) labels() []labelled {
	var out []labelled
	for _, q := range s.Quotes {
		out = append(out, labelled{q.OID, q.Label})
	}
	for _, e := range s.Extensions {
		out = append(out, labelled{s.oid(e.Suffix), e.Label})
	}
	for _, e := range s.Evidence {
		out = append(out, labelled{s.oid(e.Suffix), e.Label})
	}
	return out
}

func genGo(s *scheme) []byte {
	var b bytes.Buffer
	fmt.Fprintf(&b, "// %s\n\npackage ratls\n\n", header)
	fmt.Fprintf(&b, "// OidSchemeVersion is the version of the Privasys OID scheme these constants implement.\nconst OidSchemeVersion = %d\n\n", s.SchemeVersion)
	b.WriteString("const (\n")
	for _, q := range s.Quotes {
		fmt.Fprintf(&b, "\t// Oid%s: %s. %s\n\tOid%s = %q\n", camel(q.Name), q.Label, q.Note, camel(q.Name), q.OID)
	}
	b.WriteString(")\n\n")
	for _, a := range s.Arcs {
		if a.Number == 8 {
			continue
		}
		fmt.Fprintf(&b, "// Arc %d, %s: %s\nconst (\n", a.Number, a.Name, a.Description)
		for _, e := range s.Extensions {
			if !strings.HasPrefix(e.Suffix, fmt.Sprintf("%d.", a.Number)) {
				continue
			}
			fmt.Fprintf(&b, "\t// Oid%s is %s (%s.%s): %s.", camel(e.Name), e.Label, s.Arc, e.Suffix, e.Encoding)
			if e.Reserved {
				b.WriteString(" Reserved, never emitted.")
			}
			fmt.Fprintf(&b, "\n\tOid%s = %q\n", camel(e.Name), s.oid(e.Suffix))
		}
		b.WriteString(")\n\n")
	}
	b.WriteString("// Prefixes.\nconst (\n")
	for _, p := range s.Prefixes {
		fmt.Fprintf(&b, "\t// Oid%s: %s\n\tOid%s = %q\n", camel(p.Name), p.Description, camel(p.Name), s.oid(p.Suffix))
	}
	b.WriteString(")\n\n")
	b.WriteString("// Arc 8, evidence types: identifiers for the evidence bodies of the post-handshake\n// attest response. Never certificate extensions.\nconst (\n")
	for _, e := range s.Evidence {
		fmt.Fprintf(&b, "\t// Oid%s is %s (tee %q).\n\tOid%s = %q\n", camel(e.Name), e.Label, e.Tee, camel(e.Name), s.oid(e.Suffix))
	}
	b.WriteString(")\n\n")
	b.WriteString("// AllOids lists every extension and prefix of the scheme with its label.\nvar AllOids = []OidEntry{\n")
	for _, e := range s.Extensions {
		fmt.Fprintf(&b, "\t{OID: Oid%s, Name: %q, Label: %q, Category: %q, Reserved: %v, AppDefined: %v},\n", camel(e.Name), e.Name, e.Label, e.Category, e.Reserved, e.AppDefined)
	}
	b.WriteString("}\n\n")
	b.WriteString("// OidLabel returns a human-readable label for a known OID, or \"Unknown\".\nfunc OidLabel(oid string) string {\n\tswitch oid {\n")
	for _, l := range s.labels() {
		fmt.Fprintf(&b, "\tcase %q:\n\t\treturn %q\n", l.oid, l.label)
	}
	b.WriteString("\t}\n\tif len(oid) > len(OidAppExtensionArcPrefix) && oid[:len(OidAppExtensionArcPrefix)] == OidAppExtensionArcPrefix {\n\t\treturn \"App-defined extension \" + oid[len(OidAppExtensionArcPrefix):]\n\t}\n\treturn \"Unknown\"\n}\n")
	return b.Bytes()
}

func genRust(s *scheme) []byte {
	var b bytes.Buffer
	fmt.Fprintf(&b, "// %s\n\n", header)
	fmt.Fprintf(&b, "/// Version of the Privasys OID scheme these constants implement.\npub const OID_SCHEME_VERSION: u32 = %d;\n\n", s.SchemeVersion)
	for _, q := range s.Quotes {
		fmt.Fprintf(&b, "/// %s. %s\npub const OID_%s: &str = %q;\n", q.Label, q.Note, q.Name, q.OID)
	}
	b.WriteString("\n")
	for _, a := range s.Arcs {
		if a.Number == 8 {
			continue
		}
		fmt.Fprintf(&b, "// Arc %d, %s: %s\n", a.Number, a.Name, a.Description)
		for _, e := range s.Extensions {
			if !strings.HasPrefix(e.Suffix, fmt.Sprintf("%d.", a.Number)) {
				continue
			}
			fmt.Fprintf(&b, "/// %s (%s.%s): %s.", e.Label, s.Arc, e.Suffix, e.Encoding)
			if e.Reserved {
				b.WriteString(" Reserved, never emitted.")
			}
			fmt.Fprintf(&b, "\npub const OID_%s: &str = %q;\n", e.Name, s.oid(e.Suffix))
		}
		b.WriteString("\n")
	}
	for _, p := range s.Prefixes {
		fmt.Fprintf(&b, "/// %s\npub const OID_%s: &str = %q;\n", p.Description, p.Name, s.oid(p.Suffix))
	}
	b.WriteString("\n// Arc 8, evidence types: identifiers for the evidence bodies of the post-handshake\n// attest response. Never certificate extensions.\n")
	for _, e := range s.Evidence {
		fmt.Fprintf(&b, "/// %s (tee \"%s\").\npub const OID_%s: &str = %q;\n", e.Label, e.Tee, e.Name, s.oid(e.Suffix))
	}
	b.WriteString("\n/// One extension of the scheme.\n#[derive(Debug, Clone, Copy, PartialEq, Eq)]\npub struct OidEntry {\n    pub oid: &'static str,\n    pub name: &'static str,\n    pub label: &'static str,\n    pub category: &'static str,\n    pub reserved: bool,\n    pub app_defined: bool,\n}\n\n")
	b.WriteString("/// Every extension of the scheme with its label.\npub const ALL_OIDS: &[OidEntry] = &[\n")
	for _, e := range s.Extensions {
		fmt.Fprintf(&b, "    OidEntry { oid: OID_%s, name: %q, label: %q, category: %q, reserved: %v, app_defined: %v },\n", e.Name, e.Name, e.Label, e.Category, e.Reserved, e.AppDefined)
	}
	b.WriteString("];\n\n")
	b.WriteString("/// Human-readable label for a known OID, or \"Unknown\".\npub fn oid_label(oid: &str) -> String {\n    match oid {\n")
	for _, l := range s.labels() {
		fmt.Fprintf(&b, "        %q => %q.to_string(),\n", l.oid, l.label)
	}
	b.WriteString("        _ => {\n            if let Some(rest) = oid.strip_prefix(OID_APP_EXTENSION_ARC_PREFIX) {\n                if !rest.is_empty() {\n                    return format!(\"App-defined extension {}\", rest);\n                }\n            }\n            \"Unknown\".to_string()\n        }\n    }\n}\n")
	return b.Bytes()
}

func genTS(s *scheme) []byte {
	var b bytes.Buffer
	fmt.Fprintf(&b, "// %s\n\n", header)
	fmt.Fprintf(&b, "/** Version of the Privasys OID scheme these constants implement. */\nexport const OID_SCHEME_VERSION = %d;\n\n", s.SchemeVersion)
	for _, q := range s.Quotes {
		fmt.Fprintf(&b, "/** %s. %s */\nexport const OID_%s = %q;\n", q.Label, q.Note, q.Name, q.OID)
	}
	b.WriteString("\n")
	for _, e := range s.Extensions {
		fmt.Fprintf(&b, "/** %s (%s.%s): %s.%s */\nexport const OID_%s = %q;\n", e.Label, s.Arc, e.Suffix, e.Encoding, reservedNote(e), e.Name, s.oid(e.Suffix))
	}
	b.WriteString("\n")
	for _, p := range s.Prefixes {
		fmt.Fprintf(&b, "/** %s */\nexport const OID_%s = %q;\n", p.Description, p.Name, s.oid(p.Suffix))
	}
	b.WriteString("\n")
	for _, e := range s.Evidence {
		fmt.Fprintf(&b, "/** %s (tee \"%s\"). Evidence type, never a certificate extension. */\nexport const OID_%s = %q;\n", e.Label, e.Tee, e.Name, s.oid(e.Suffix))
	}
	b.WriteString("\nexport interface OidEntry {\n  oid: string;\n  name: string;\n  label: string;\n  category: string;\n  reserved: boolean;\n  appDefined: boolean;\n}\n\n")
	b.WriteString("/** Every extension of the scheme with its label. */\nexport const ALL_OIDS: readonly OidEntry[] = [\n")
	for _, e := range s.Extensions {
		fmt.Fprintf(&b, "  { oid: OID_%s, name: %q, label: %q, category: %q, reserved: %v, appDefined: %v },\n", e.Name, e.Name, e.Label, e.Category, e.Reserved, e.AppDefined)
	}
	b.WriteString("];\n\n")
	b.WriteString("const LABELS: Record<string, string> = {\n")
	for _, l := range s.labels() {
		fmt.Fprintf(&b, "  %q: %q,\n", l.oid, l.label)
	}
	b.WriteString("};\n\n/** Human-readable label for a known OID, or \"Unknown\". */\nexport function oidLabel(oid: string): string {\n  const known = LABELS[oid];\n  if (known) return known;\n  if (oid.startsWith(OID_APP_EXTENSION_ARC_PREFIX) && oid.length > OID_APP_EXTENSION_ARC_PREFIX.length) {\n    return `App-defined extension ${oid.slice(OID_APP_EXTENSION_ARC_PREFIX.length)}`;\n  }\n  return \"Unknown\";\n}\n")
	return b.Bytes()
}

func genPython(s *scheme) []byte {
	var b bytes.Buffer
	fmt.Fprintf(&b, "# %s\n\n", header)
	fmt.Fprintf(&b, "OID_SCHEME_VERSION = %d\n\n", s.SchemeVersion)
	for _, q := range s.Quotes {
		fmt.Fprintf(&b, "# %s. %s\nOID_%s = %q\n", q.Label, q.Note, q.Name, q.OID)
	}
	b.WriteString("\n")
	for _, e := range s.Extensions {
		fmt.Fprintf(&b, "# %s (%s.%s): %s.%s\nOID_%s = %q\n", e.Label, s.Arc, e.Suffix, e.Encoding, reservedNote(e), e.Name, s.oid(e.Suffix))
	}
	b.WriteString("\n")
	for _, p := range s.Prefixes {
		fmt.Fprintf(&b, "# %s\nOID_%s = %q\n", p.Description, p.Name, s.oid(p.Suffix))
	}
	b.WriteString("\n")
	for _, e := range s.Evidence {
		fmt.Fprintf(&b, "# %s (tee \"%s\"). Evidence type, never a certificate extension.\nOID_%s = %q\n", e.Label, e.Tee, e.Name, s.oid(e.Suffix))
	}
	b.WriteString("\nALL_OIDS = [\n")
	for _, e := range s.Extensions {
		fmt.Fprintf(&b, "    {\"oid\": OID_%s, \"name\": %q, \"label\": %q, \"category\": %q, \"reserved\": %s, \"app_defined\": %s},\n", e.Name, e.Name, e.Label, e.Category, pyBool(e.Reserved), pyBool(e.AppDefined))
	}
	b.WriteString("]\n\nOID_LABELS = {\n")
	for _, l := range s.labels() {
		fmt.Fprintf(&b, "    %q: %q,\n", l.oid, l.label)
	}
	b.WriteString("}\n\n\ndef oid_label(oid: str) -> str:\n    \"\"\"Human-readable label for a known OID, or \"Unknown\".\"\"\"\n    known = OID_LABELS.get(oid)\n    if known:\n        return known\n    if oid.startswith(OID_APP_EXTENSION_ARC_PREFIX) and len(oid) > len(OID_APP_EXTENSION_ARC_PREFIX):\n        return \"App-defined extension \" + oid[len(OID_APP_EXTENSION_ARC_PREFIX):]\n    return \"Unknown\"\n")
	return b.Bytes()
}

func genCSharp(s *scheme) []byte {
	var b bytes.Buffer
	fmt.Fprintf(&b, "// %s\n\nusing System.Collections.Generic;\n\nnamespace Privasys.RaTls\n{\n    /// <summary>Privasys X.509 OID scheme v%d.</summary>\n    public static class Oids\n    {\n", header, s.SchemeVersion)
	fmt.Fprintf(&b, "        public const int SchemeVersion = %d;\n\n", s.SchemeVersion)
	for _, q := range s.Quotes {
		fmt.Fprintf(&b, "        /// <summary>%s. %s</summary>\n        public const string %s = %q;\n", q.Label, q.Note, camel(q.Name), q.OID)
	}
	b.WriteString("\n")
	for _, e := range s.Extensions {
		fmt.Fprintf(&b, "        /// <summary>%s (%s.%s): %s.%s</summary>\n        public const string %s = %q;\n", e.Label, s.Arc, e.Suffix, e.Encoding, reservedNote(e), camel(e.Name), s.oid(e.Suffix))
	}
	b.WriteString("\n")
	for _, p := range s.Prefixes {
		fmt.Fprintf(&b, "        /// <summary>%s</summary>\n        public const string %s = %q;\n", p.Description, camel(p.Name), s.oid(p.Suffix))
	}
	b.WriteString("\n")
	for _, e := range s.Evidence {
		fmt.Fprintf(&b, "        /// <summary>%s (tee \"%s\"). Evidence type, never a certificate extension.</summary>\n        public const string %s = %q;\n", e.Label, e.Tee, camel(e.Name), s.oid(e.Suffix))
	}
	b.WriteString("\n        public static readonly IReadOnlyDictionary<string, string> Labels = new Dictionary<string, string>\n        {\n")
	for _, l := range s.labels() {
		fmt.Fprintf(&b, "            [%q] = %q,\n", l.oid, l.label)
	}
	b.WriteString("        };\n\n        /// <summary>Human-readable label for a known OID, or \"Unknown\".</summary>\n        public static string Label(string oid)\n        {\n            if (Labels.TryGetValue(oid, out var label)) return label;\n            if (oid.StartsWith(AppExtensionArcPrefix) && oid.Length > AppExtensionArcPrefix.Length)\n                return \"App-defined extension \" + oid.Substring(AppExtensionArcPrefix.Length);\n            return \"Unknown\";\n        }\n    }\n}\n")
	return b.Bytes()
}

func genDocs(s *scheme) []byte {
	var b bytes.Buffer
	fmt.Fprintf(&b, "# Privasys X.509 OID scheme v%d\n\n<!-- %s -->\n\n", s.SchemeVersion, header)
	fmt.Fprintf(&b, "Arc `%s`. One slot, one meaning, on both editions; numbers are contiguous within an arc; a retired slot is never reused; evidence is never a certificate extension; the app-defined sub-arc root (5.4) never carries a value. The v1 column is documentation for reading old certificates and old records; the SDKs parse v2 only.\n\n", s.Arc)
	for _, a := range s.Arcs {
		if a.Number == 8 {
			continue
		}
		fmt.Fprintf(&b, "## Arc %d, %s\n\n%s\n\n| OID | Name | Label | Encoding | Mini | Virtual | v1 |\n|---|---|---|---|---|---|---|\n", a.Number, a.Name, a.Description)
		for _, e := range s.Extensions {
			if !strings.HasPrefix(e.Suffix, fmt.Sprintf("%d.", a.Number)) {
				continue
			}
			v1 := "new"
			if e.V1 != nil {
				v1 = *e.V1
			}
			fmt.Fprintf(&b, "| `%s` | `%s` | %s | %s | %s | %s | %s |\n", e.Suffix, e.Name, e.Label, e.Encoding, yn(e.Mini), yn(e.Virtual), v1)
		}
		b.WriteString("\n")
	}
	b.WriteString("## Prefixes\n\n| Prefix | Name | Description |\n|---|---|---|\n")
	for _, p := range s.Prefixes {
		fmt.Fprintf(&b, "| `%s` | `%s` | %s |\n", s.oid(p.Suffix), p.Name, p.Description)
	}
	b.WriteString("\n## Arc 8, Evidence types\n\nIdentifiers for the evidence bodies served by the post-handshake attest response (`docs/ratls-v2.md`). Never certificate extensions.\n\n| OID | Name | Label | `tee` | v1 |\n|---|---|---|---|---|\n")
	for _, e := range s.Evidence {
		fmt.Fprintf(&b, "| `%s` | `%s` | %s | `%s` | %s |\n", e.Suffix, e.Name, e.Label, e.Tee, e.V1)
	}
	b.WriteString("\n## Quote extensions of v1 (Intel arc)\n\n| OID | Name | Note |\n|---|---|---|\n")
	for _, q := range s.Quotes {
		fmt.Fprintf(&b, "| `%s` | `%s` | %s |\n", q.OID, q.Name, q.Note)
	}
	b.WriteString("\n## Retired v1 slots\n\n| v1 | Was | Note |\n|---|---|---|\n")
	for _, r := range s.Retired {
		fmt.Fprintf(&b, "| `%s` | %s | %s |\n", r.V1, r.Was, r.Note)
	}
	return b.Bytes()
}

func reservedNote(e extension) string {
	if e.Reserved {
		return " Reserved, never emitted."
	}
	return ""
}

func pyBool(v bool) string {
	if v {
		return "True"
	}
	return "False"
}

func yn(v bool) string {
	if v {
		return "yes"
	}
	return "no"
}

func validate(s *scheme) error {
	seen := map[string]string{}
	for _, e := range s.Extensions {
		if prev, ok := seen[e.Suffix]; ok {
			return fmt.Errorf("suffix %s used by %s and %s", e.Suffix, prev, e.Name)
		}
		seen[e.Suffix] = e.Name
	}
	// Contiguity within each arc for top-level slots (x.y).
	byArc := map[string][]int{}
	for _, e := range s.Extensions {
		parts := strings.Split(e.Suffix, ".")
		if len(parts) != 2 {
			continue
		}
		var n int
		fmt.Sscanf(parts[1], "%d", &n)
		byArc[parts[0]] = append(byArc[parts[0]], n)
	}
	for a, ns := range byArc {
		sort.Ints(ns)
		for i, n := range ns {
			if n != i+1 {
				return fmt.Errorf("arc %s is not contiguous: slots %v", a, ns)
			}
		}
	}
	return nil
}

func main() {
	root := flag.String("root", ".", "repository root (where oids.json lives)")
	check := flag.Bool("check", false, "fail if any generated file differs")
	flag.Parse()

	raw, err := os.ReadFile(filepath.Join(*root, "oids.json"))
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(2)
	}
	var s scheme
	if err := json.Unmarshal(raw, &s); err != nil {
		fmt.Fprintln(os.Stderr, "oids.json:", err)
		os.Exit(2)
	}
	if err := validate(&s); err != nil {
		fmt.Fprintln(os.Stderr, "oids.json:", err)
		os.Exit(2)
	}

	outputs := map[string][]byte{
		"go/ratls/oids_gen.go":   genGo(&s),
		"rust/src/oids_gen.rs":   genRust(&s),
		"typescript/oids_gen.ts": genTS(&s),
		"python/oids_gen.py":     genPython(&s),
		"dotnet/OidsGen.cs":      genCSharp(&s),
		"docs/oids.md":           genDocs(&s),
	}
	stale := 0
	for rel, content := range outputs {
		path := filepath.Join(*root, rel)
		if *check {
			cur, err := os.ReadFile(path)
			if err != nil || !bytes.Equal(bytes.ReplaceAll(cur, []byte("\r\n"), []byte("\n")), content) {
				fmt.Fprintf(os.Stderr, "stale: %s\n", rel)
				stale++
			}
			continue
		}
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(2)
		}
		if err := os.WriteFile(path, content, 0o644); err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(2)
		}
		fmt.Println("wrote", rel)
	}
	if stale > 0 {
		fmt.Fprintf(os.Stderr, "%d generated file(s) stale: run `cd go && go run ./cmd/oidgen -root ..`\n", stale)
		os.Exit(1)
	}
}
