// Code generated by oidgen from oids.json; DO NOT EDIT.

using System.Collections.Generic;

namespace Privasys.RaTls
{
    /// <summary>Privasys X.509 OID scheme v2.</summary>
    public static class Oids
    {
        public const int SchemeVersion = 2;

        /// <summary>SGX Quote. Intel arc. A v1 certificate extension; in v2 the quote travels in the attest response and a leaf that carries it is a v1 leaf (rejected).</summary>
        public const string SGXQuote = "1.2.840.113741.1.13.1.0";
        /// <summary>TDX Quote. Intel arc. Same status as SGX_QUOTE.</summary>
        public const string TDXQuote = "1.2.840.113741.1.5.5.1.6";

        /// <summary>Runtime Version Hash (1.3.6.1.4.1.65230.1.1): 32 bytes, SHA-256 of the runtime version (Wasmtime on Mini, containerd on Virtual).</summary>
        public const string RuntimeVersionHash = "1.3.6.1.4.1.65230.1.1";
        /// <summary>Image Profile (1.3.6.1.4.1.65230.1.2): UTF-8 string, "production" or "dev".</summary>
        public const string ImageProfile = "1.3.6.1.4.1.65230.1.2";
        /// <summary>Enclave Instance ID (1.3.6.1.4.1.65230.1.3): 16-byte UUID, the management-service enclave_id received at registration.</summary>
        public const string EnclaveInstanceID = "1.3.6.1.4.1.65230.1.3";
        /// <summary>Platform Owner (1.3.6.1.4.1.65230.1.4): reserved for the owner identifier a platform ownership endorsement attests; the endorsement itself is evidence (8.5), and the identity of the machine stays in the quote (PCK certificate, SEV-SNP CHIP_ID, GPU device certificate). Reserved, never emitted.</summary>
        public const string PlatformOwner = "1.3.6.1.4.1.65230.1.4";
        /// <summary>Config Merkle Root (1.3.6.1.4.1.65230.2.1): 32 bytes, root over every configuration input of the platform.</summary>
        public const string ConfigMerkleRoot = "1.3.6.1.4.1.65230.2.1";
        /// <summary>Egress CA Bundle Hash (1.3.6.1.4.1.65230.2.2): 32 bytes, SHA-256 of the outbound trust-anchor bundle.</summary>
        public const string EgressCAHash = "1.3.6.1.4.1.65230.2.2";
        /// <summary>Attestation Servers Hash (1.3.6.1.4.1.65230.2.3): 32 bytes, SHA-256 of the sorted attestation server URL list.</summary>
        public const string AttestationServersHash = "1.3.6.1.4.1.65230.2.3";
        /// <summary>Combined Workloads Hash (1.3.6.1.4.1.65230.2.4): 32 bytes, SHA-256 over the loaded workload set.</summary>
        public const string CombinedWorkloadsHash = "1.3.6.1.4.1.65230.2.4";
        /// <summary>Data Encryption Key Origin (1.3.6.1.4.1.65230.3.1): UTF-8 string, "byok:<fingerprint>" or "generated".</summary>
        public const string DEKOrigin = "1.3.6.1.4.1.65230.3.1";
        /// <summary>Authenticated State Root (1.3.6.1.4.1.65230.3.2): 40 bytes, 32-byte Merkle root followed by a big-endian u64 version.</summary>
        public const string AuthenticatedStateRoot = "1.3.6.1.4.1.65230.3.2";
        /// <summary>Workload App ID (1.3.6.1.4.1.65230.4.1): 16-byte UUID, the management app id.</summary>
        public const string WorkloadAppID = "1.3.6.1.4.1.65230.4.1";
        /// <summary>Workload Code Digest (1.3.6.1.4.1.65230.4.2): 32 bytes, SHA-256 of the WASM bytecode (Mini) or of the OCI manifest (Virtual).</summary>
        public const string WorkloadCodeHash = "1.3.6.1.4.1.65230.4.2";
        /// <summary>Workload Image Ref (1.3.6.1.4.1.65230.4.3): UTF-8 string, image reference without digest.</summary>
        public const string WorkloadImageRef = "1.3.6.1.4.1.65230.4.3";
        /// <summary>Workload Config Merkle Root (1.3.6.1.4.1.65230.5.1): 32 bytes.</summary>
        public const string WorkloadConfigMerkleRoot = "1.3.6.1.4.1.65230.5.1";
        /// <summary>Workload Configuration Hash (1.3.6.1.4.1.65230.5.2): 32 bytes, runtime-stamped hash of the workload configuration.</summary>
        public const string WorkloadConfigurationHash = "1.3.6.1.4.1.65230.5.2";
        /// <summary>Reserved (1.3.6.1.4.1.65230.5.3): reserved. Reserved, never emitted.</summary>
        public const string WorkloadReserved53 = "1.3.6.1.4.1.65230.5.3";
        /// <summary>Model Digest (1.3.6.1.4.1.65230.5.4.5): app-defined (SDK set-attestation-extension), 32 bytes.</summary>
        public const string WorkloadModelDigest = "1.3.6.1.4.1.65230.5.4.5";
        /// <summary>Tools Digest (1.3.6.1.4.1.65230.5.4.7): app-defined (SDK set-attestation-extension), 32 bytes.</summary>
        public const string WorkloadToolsDigest = "1.3.6.1.4.1.65230.5.4.7";
        /// <summary>Policy Digest (1.3.6.1.4.1.65230.5.4.9): app-defined (SDK set-attestation-extension), 32 bytes, SHA-256 of the workload's active service-ceiling policy document.</summary>
        public const string WorkloadPolicyDigest = "1.3.6.1.4.1.65230.5.4.9";
        /// <summary>Workload Key Source (1.3.6.1.4.1.65230.6.1): UTF-8 string, "byok:<fingerprint>", "generated" or "vault:<path>".</summary>
        public const string WorkloadKeySource = "1.3.6.1.4.1.65230.6.1";
        /// <summary>Workload State Root (1.3.6.1.4.1.65230.6.2): reserved, mirrors 3.2 for per-workload authenticated stores. Reserved, never emitted.</summary>
        public const string WorkloadStateRoot = "1.3.6.1.4.1.65230.6.2";
        /// <summary>Attested Dependency Set (1.3.6.1.4.1.65230.7.1): canonical dependency-set encoding (EncodeDependencySet), written by the runtime.</summary>
        public const string AttestedDependencySet = "1.3.6.1.4.1.65230.7.1";
        /// <summary>Allowed Callers (1.3.6.1.4.1.65230.7.2): reserved, enforced from the management database today. Reserved, never emitted.</summary>
        public const string AllowedCallers = "1.3.6.1.4.1.65230.7.2";

        /// <summary>The whole Privasys private-enterprise arc, with a trailing dot. Membership in CertInfo.CustomOids is by arc, not by allowlist.</summary>
        public const string PrivasysArcPrefix = "1.3.6.1.4.1.65230.";
        /// <summary>Sub-arc apps publish attested digests under, through the SDK set-attestation-extension call. Open-ended by design; the root 5.4 never carries a value.</summary>
        public const string AppExtensionArcPrefix = "1.3.6.1.4.1.65230.5.4.";

        /// <summary>Intel SGX DCAP quote (tee "sgx"). Evidence type, never a certificate extension.</summary>
        public const string EvidenceSGXQuote = "1.3.6.1.4.1.65230.8.1";
        /// <summary>Intel TDX DCAP quote (tee "tdx"). Evidence type, never a certificate extension.</summary>
        public const string EvidenceTDXQuote = "1.3.6.1.4.1.65230.8.2";
        /// <summary>AMD SEV-SNP report (tee "sev-snp"). Evidence type, never a certificate extension.</summary>
        public const string EvidenceSEVSNPReport = "1.3.6.1.4.1.65230.8.3";
        /// <summary>NVIDIA GPU CC evidence (tee "nvidia-gpu"). Evidence type, never a certificate extension.</summary>
        public const string EvidenceNVIDIAGPU = "1.3.6.1.4.1.65230.8.4";
        /// <summary>Platform ownership endorsement (tee "intel-poe"). Evidence type, never a certificate extension.</summary>
        public const string EvidencePlatformOwnershipEndorsement = "1.3.6.1.4.1.65230.8.5";

        public static readonly IReadOnlyDictionary<string, string> Labels = new Dictionary<string, string>
        {
            ["1.2.840.113741.1.13.1.0"] = "SGX Quote",
            ["1.2.840.113741.1.5.5.1.6"] = "TDX Quote",
            ["1.3.6.1.4.1.65230.1.1"] = "Runtime Version Hash",
            ["1.3.6.1.4.1.65230.1.2"] = "Image Profile",
            ["1.3.6.1.4.1.65230.1.3"] = "Enclave Instance ID",
            ["1.3.6.1.4.1.65230.1.4"] = "Platform Owner",
            ["1.3.6.1.4.1.65230.2.1"] = "Config Merkle Root",
            ["1.3.6.1.4.1.65230.2.2"] = "Egress CA Bundle Hash",
            ["1.3.6.1.4.1.65230.2.3"] = "Attestation Servers Hash",
            ["1.3.6.1.4.1.65230.2.4"] = "Combined Workloads Hash",
            ["1.3.6.1.4.1.65230.3.1"] = "Data Encryption Key Origin",
            ["1.3.6.1.4.1.65230.3.2"] = "Authenticated State Root",
            ["1.3.6.1.4.1.65230.4.1"] = "Workload App ID",
            ["1.3.6.1.4.1.65230.4.2"] = "Workload Code Digest",
            ["1.3.6.1.4.1.65230.4.3"] = "Workload Image Ref",
            ["1.3.6.1.4.1.65230.5.1"] = "Workload Config Merkle Root",
            ["1.3.6.1.4.1.65230.5.2"] = "Workload Configuration Hash",
            ["1.3.6.1.4.1.65230.5.3"] = "Reserved",
            ["1.3.6.1.4.1.65230.5.4.5"] = "Model Digest",
            ["1.3.6.1.4.1.65230.5.4.7"] = "Tools Digest",
            ["1.3.6.1.4.1.65230.5.4.9"] = "Policy Digest",
            ["1.3.6.1.4.1.65230.6.1"] = "Workload Key Source",
            ["1.3.6.1.4.1.65230.6.2"] = "Workload State Root",
            ["1.3.6.1.4.1.65230.7.1"] = "Attested Dependency Set",
            ["1.3.6.1.4.1.65230.7.2"] = "Allowed Callers",
            ["1.3.6.1.4.1.65230.8.1"] = "Intel SGX DCAP quote",
            ["1.3.6.1.4.1.65230.8.2"] = "Intel TDX DCAP quote",
            ["1.3.6.1.4.1.65230.8.3"] = "AMD SEV-SNP report",
            ["1.3.6.1.4.1.65230.8.4"] = "NVIDIA GPU CC evidence",
            ["1.3.6.1.4.1.65230.8.5"] = "Platform ownership endorsement",
        };

        /// <summary>Human-readable label for a known OID, or "Unknown".</summary>
        public static string Label(string oid)
        {
            if (Labels.TryGetValue(oid, out var label)) return label;
            if (oid.StartsWith(AppExtensionArcPrefix) && oid.Length > AppExtensionArcPrefix.Length)
                return "App-defined extension " + oid.Substring(AppExtensionArcPrefix.Length);
            return "Unknown";
        }
    }
}
