# Code generated by oidgen from oids.json; DO NOT EDIT.

OID_SCHEME_VERSION = 2

# SGX Quote. Intel arc. A v1 certificate extension; in v2 the quote travels in the attest response and a leaf that carries it is a v1 leaf (rejected).
OID_SGX_QUOTE = "1.2.840.113741.1.13.1.0"
# TDX Quote. Intel arc. Same status as SGX_QUOTE.
OID_TDX_QUOTE = "1.2.840.113741.1.5.5.1.6"

# Runtime Version Hash (1.3.6.1.4.1.65230.1.1): 32 bytes, SHA-256 of the runtime version (Wasmtime on Mini, containerd on Virtual).
OID_RUNTIME_VERSION_HASH = "1.3.6.1.4.1.65230.1.1"
# Image Profile (1.3.6.1.4.1.65230.1.2): UTF-8 string, "production" or "dev".
OID_IMAGE_PROFILE = "1.3.6.1.4.1.65230.1.2"
# Enclave Instance ID (1.3.6.1.4.1.65230.1.3): 16-byte UUID, the management-service enclave_id received at registration.
OID_ENCLAVE_INSTANCE_ID = "1.3.6.1.4.1.65230.1.3"
# Platform Hardware Identity (1.3.6.1.4.1.65230.1.4): reserved for Platform Ownership Endorsements. Reserved, never emitted.
OID_PLATFORM_HARDWARE_IDENTITY = "1.3.6.1.4.1.65230.1.4"
# Config Merkle Root (1.3.6.1.4.1.65230.2.1): 32 bytes, root over every configuration input of the platform.
OID_CONFIG_MERKLE_ROOT = "1.3.6.1.4.1.65230.2.1"
# Egress CA Bundle Hash (1.3.6.1.4.1.65230.2.2): 32 bytes, SHA-256 of the outbound trust-anchor bundle.
OID_EGRESS_CA_HASH = "1.3.6.1.4.1.65230.2.2"
# Attestation Servers Hash (1.3.6.1.4.1.65230.2.3): 32 bytes, SHA-256 of the sorted attestation server URL list.
OID_ATTESTATION_SERVERS_HASH = "1.3.6.1.4.1.65230.2.3"
# Combined Workloads Hash (1.3.6.1.4.1.65230.2.4): 32 bytes, SHA-256 over the loaded workload set.
OID_COMBINED_WORKLOADS_HASH = "1.3.6.1.4.1.65230.2.4"
# Data Encryption Key Origin (1.3.6.1.4.1.65230.3.1): UTF-8 string, "byok:<fingerprint>" or "generated".
OID_DEK_ORIGIN = "1.3.6.1.4.1.65230.3.1"
# Authenticated State Root (1.3.6.1.4.1.65230.3.2): 40 bytes, 32-byte Merkle root followed by a big-endian u64 version.
OID_AUTHENTICATED_STATE_ROOT = "1.3.6.1.4.1.65230.3.2"
# Workload App ID (1.3.6.1.4.1.65230.4.1): 16-byte UUID, the management app id.
OID_WORKLOAD_APP_ID = "1.3.6.1.4.1.65230.4.1"
# Workload Code Digest (1.3.6.1.4.1.65230.4.2): 32 bytes, SHA-256 of the WASM bytecode (Mini) or of the OCI manifest (Virtual).
OID_WORKLOAD_CODE_HASH = "1.3.6.1.4.1.65230.4.2"
# Workload Image Ref (1.3.6.1.4.1.65230.4.3): UTF-8 string, image reference without digest.
OID_WORKLOAD_IMAGE_REF = "1.3.6.1.4.1.65230.4.3"
# Workload Config Merkle Root (1.3.6.1.4.1.65230.5.1): 32 bytes.
OID_WORKLOAD_CONFIG_MERKLE_ROOT = "1.3.6.1.4.1.65230.5.1"
# Workload Configuration Hash (1.3.6.1.4.1.65230.5.2): 32 bytes, runtime-stamped hash of the workload configuration.
OID_WORKLOAD_CONFIGURATION_HASH = "1.3.6.1.4.1.65230.5.2"
# Reserved (1.3.6.1.4.1.65230.5.3): reserved. Reserved, never emitted.
OID_WORKLOAD_RESERVED_5_3 = "1.3.6.1.4.1.65230.5.3"
# Model Digest (1.3.6.1.4.1.65230.5.4.5): app-defined (SDK set-attestation-extension), 32 bytes.
OID_WORKLOAD_MODEL_DIGEST = "1.3.6.1.4.1.65230.5.4.5"
# Tools Digest (1.3.6.1.4.1.65230.5.4.7): app-defined (SDK set-attestation-extension), 32 bytes.
OID_WORKLOAD_TOOLS_DIGEST = "1.3.6.1.4.1.65230.5.4.7"
# Workload Key Source (1.3.6.1.4.1.65230.6.1): UTF-8 string, "byok:<fingerprint>", "generated" or "vault:<path>".
OID_WORKLOAD_KEY_SOURCE = "1.3.6.1.4.1.65230.6.1"
# Workload State Root (1.3.6.1.4.1.65230.6.2): reserved, mirrors 3.2 for per-workload authenticated stores. Reserved, never emitted.
OID_WORKLOAD_STATE_ROOT = "1.3.6.1.4.1.65230.6.2"
# Attested Dependency Set (1.3.6.1.4.1.65230.7.1): canonical dependency-set encoding (EncodeDependencySet), written by the runtime.
OID_ATTESTED_DEPENDENCY_SET = "1.3.6.1.4.1.65230.7.1"
# Allowed Callers (1.3.6.1.4.1.65230.7.2): reserved, enforced from the management database today. Reserved, never emitted.
OID_ALLOWED_CALLERS = "1.3.6.1.4.1.65230.7.2"

# The whole Privasys private-enterprise arc, with a trailing dot. Membership in CertInfo.CustomOids is by arc, not by allowlist.
OID_PRIVASYS_ARC_PREFIX = "1.3.6.1.4.1.65230."
# Sub-arc apps publish attested digests under, through the SDK set-attestation-extension call. Open-ended by design; the root 5.4 never carries a value.
OID_APP_EXTENSION_ARC_PREFIX = "1.3.6.1.4.1.65230.5.4."

# Intel SGX DCAP quote (tee "sgx"). Evidence type, never a certificate extension.
OID_EVIDENCE_SGX_QUOTE = "1.3.6.1.4.1.65230.8.1"
# Intel TDX DCAP quote (tee "tdx"). Evidence type, never a certificate extension.
OID_EVIDENCE_TDX_QUOTE = "1.3.6.1.4.1.65230.8.2"
# AMD SEV-SNP report (tee "sev-snp"). Evidence type, never a certificate extension.
OID_EVIDENCE_SEV_SNP_REPORT = "1.3.6.1.4.1.65230.8.3"
# NVIDIA GPU CC evidence (tee "nvidia-gpu"). Evidence type, never a certificate extension.
OID_EVIDENCE_NVIDIA_GPU = "1.3.6.1.4.1.65230.8.4"

ALL_OIDS = [
    {"oid": OID_RUNTIME_VERSION_HASH, "name": "RUNTIME_VERSION_HASH", "label": "Runtime Version Hash", "category": "platform-identity", "reserved": False, "app_defined": False},
    {"oid": OID_IMAGE_PROFILE, "name": "IMAGE_PROFILE", "label": "Image Profile", "category": "platform-identity", "reserved": False, "app_defined": False},
    {"oid": OID_ENCLAVE_INSTANCE_ID, "name": "ENCLAVE_INSTANCE_ID", "label": "Enclave Instance ID", "category": "platform-identity", "reserved": False, "app_defined": False},
    {"oid": OID_PLATFORM_HARDWARE_IDENTITY, "name": "PLATFORM_HARDWARE_IDENTITY", "label": "Platform Hardware Identity", "category": "platform-identity", "reserved": True, "app_defined": False},
    {"oid": OID_CONFIG_MERKLE_ROOT, "name": "CONFIG_MERKLE_ROOT", "label": "Config Merkle Root", "category": "platform-configuration", "reserved": False, "app_defined": False},
    {"oid": OID_EGRESS_CA_HASH, "name": "EGRESS_CA_HASH", "label": "Egress CA Bundle Hash", "category": "platform-configuration", "reserved": False, "app_defined": False},
    {"oid": OID_ATTESTATION_SERVERS_HASH, "name": "ATTESTATION_SERVERS_HASH", "label": "Attestation Servers Hash", "category": "platform-configuration", "reserved": False, "app_defined": False},
    {"oid": OID_COMBINED_WORKLOADS_HASH, "name": "COMBINED_WORKLOADS_HASH", "label": "Combined Workloads Hash", "category": "platform-configuration", "reserved": False, "app_defined": False},
    {"oid": OID_DEK_ORIGIN, "name": "DEK_ORIGIN", "label": "Data Encryption Key Origin", "category": "platform-keys-state", "reserved": False, "app_defined": False},
    {"oid": OID_AUTHENTICATED_STATE_ROOT, "name": "AUTHENTICATED_STATE_ROOT", "label": "Authenticated State Root", "category": "platform-keys-state", "reserved": False, "app_defined": False},
    {"oid": OID_WORKLOAD_APP_ID, "name": "WORKLOAD_APP_ID", "label": "Workload App ID", "category": "workload-identity", "reserved": False, "app_defined": False},
    {"oid": OID_WORKLOAD_CODE_HASH, "name": "WORKLOAD_CODE_HASH", "label": "Workload Code Digest", "category": "workload-identity", "reserved": False, "app_defined": False},
    {"oid": OID_WORKLOAD_IMAGE_REF, "name": "WORKLOAD_IMAGE_REF", "label": "Workload Image Ref", "category": "workload-identity", "reserved": False, "app_defined": False},
    {"oid": OID_WORKLOAD_CONFIG_MERKLE_ROOT, "name": "WORKLOAD_CONFIG_MERKLE_ROOT", "label": "Workload Config Merkle Root", "category": "workload-configuration", "reserved": False, "app_defined": False},
    {"oid": OID_WORKLOAD_CONFIGURATION_HASH, "name": "WORKLOAD_CONFIGURATION_HASH", "label": "Workload Configuration Hash", "category": "workload-configuration", "reserved": False, "app_defined": False},
    {"oid": OID_WORKLOAD_RESERVED_5_3, "name": "WORKLOAD_RESERVED_5_3", "label": "Reserved", "category": "workload-configuration", "reserved": True, "app_defined": False},
    {"oid": OID_WORKLOAD_MODEL_DIGEST, "name": "WORKLOAD_MODEL_DIGEST", "label": "Model Digest", "category": "workload-configuration", "reserved": False, "app_defined": True},
    {"oid": OID_WORKLOAD_TOOLS_DIGEST, "name": "WORKLOAD_TOOLS_DIGEST", "label": "Tools Digest", "category": "workload-configuration", "reserved": False, "app_defined": True},
    {"oid": OID_WORKLOAD_KEY_SOURCE, "name": "WORKLOAD_KEY_SOURCE", "label": "Workload Key Source", "category": "workload-keys-state", "reserved": False, "app_defined": False},
    {"oid": OID_WORKLOAD_STATE_ROOT, "name": "WORKLOAD_STATE_ROOT", "label": "Workload State Root", "category": "workload-keys-state", "reserved": True, "app_defined": False},
    {"oid": OID_ATTESTED_DEPENDENCY_SET, "name": "ATTESTED_DEPENDENCY_SET", "label": "Attested Dependency Set", "category": "trust", "reserved": False, "app_defined": False},
    {"oid": OID_ALLOWED_CALLERS, "name": "ALLOWED_CALLERS", "label": "Allowed Callers", "category": "trust", "reserved": True, "app_defined": False},
]

OID_LABELS = {
    "1.2.840.113741.1.13.1.0": "SGX Quote",
    "1.2.840.113741.1.5.5.1.6": "TDX Quote",
    "1.3.6.1.4.1.65230.1.1": "Runtime Version Hash",
    "1.3.6.1.4.1.65230.1.2": "Image Profile",
    "1.3.6.1.4.1.65230.1.3": "Enclave Instance ID",
    "1.3.6.1.4.1.65230.1.4": "Platform Hardware Identity",
    "1.3.6.1.4.1.65230.2.1": "Config Merkle Root",
    "1.3.6.1.4.1.65230.2.2": "Egress CA Bundle Hash",
    "1.3.6.1.4.1.65230.2.3": "Attestation Servers Hash",
    "1.3.6.1.4.1.65230.2.4": "Combined Workloads Hash",
    "1.3.6.1.4.1.65230.3.1": "Data Encryption Key Origin",
    "1.3.6.1.4.1.65230.3.2": "Authenticated State Root",
    "1.3.6.1.4.1.65230.4.1": "Workload App ID",
    "1.3.6.1.4.1.65230.4.2": "Workload Code Digest",
    "1.3.6.1.4.1.65230.4.3": "Workload Image Ref",
    "1.3.6.1.4.1.65230.5.1": "Workload Config Merkle Root",
    "1.3.6.1.4.1.65230.5.2": "Workload Configuration Hash",
    "1.3.6.1.4.1.65230.5.3": "Reserved",
    "1.3.6.1.4.1.65230.5.4.5": "Model Digest",
    "1.3.6.1.4.1.65230.5.4.7": "Tools Digest",
    "1.3.6.1.4.1.65230.6.1": "Workload Key Source",
    "1.3.6.1.4.1.65230.6.2": "Workload State Root",
    "1.3.6.1.4.1.65230.7.1": "Attested Dependency Set",
    "1.3.6.1.4.1.65230.7.2": "Allowed Callers",
    "1.3.6.1.4.1.65230.8.1": "Intel SGX DCAP quote",
    "1.3.6.1.4.1.65230.8.2": "Intel TDX DCAP quote",
    "1.3.6.1.4.1.65230.8.3": "AMD SEV-SNP report",
    "1.3.6.1.4.1.65230.8.4": "NVIDIA GPU CC evidence",
}


def oid_label(oid: str) -> str:
    """Human-readable label for a known OID, or "Unknown"."""
    known = OID_LABELS.get(oid)
    if known:
        return known
    if oid.startswith(OID_APP_EXTENSION_ARC_PREFIX) and len(oid) > len(OID_APP_EXTENSION_ARC_PREFIX):
        return "App-defined extension " + oid[len(OID_APP_EXTENSION_ARC_PREFIX):]
    return "Unknown"
