// Code generated by oidgen from oids.json; DO NOT EDIT.

package ratls

// OidSchemeVersion is the version of the Privasys OID scheme these constants implement.
const OidSchemeVersion = 2

const (
	// OidSGXQuote: SGX Quote. Intel arc. A v1 certificate extension; in v2 the quote travels in the attest response and a leaf that carries it is a v1 leaf (rejected).
	OidSGXQuote = "1.2.840.113741.1.13.1.0"
	// OidTDXQuote: TDX Quote. Intel arc. Same status as SGX_QUOTE.
	OidTDXQuote = "1.2.840.113741.1.5.5.1.6"
)

// Arc 1, Platform identity: What runs here, which instance.
const (
	// OidRuntimeVersionHash is Runtime Version Hash (1.3.6.1.4.1.65230.1.1): 32 bytes, SHA-256 of the runtime version (Wasmtime on Mini, containerd on Virtual).
	OidRuntimeVersionHash = "1.3.6.1.4.1.65230.1.1"
	// OidImageProfile is Image Profile (1.3.6.1.4.1.65230.1.2): UTF-8 string, "production" or "dev".
	OidImageProfile = "1.3.6.1.4.1.65230.1.2"
	// OidEnclaveInstanceID is Enclave Instance ID (1.3.6.1.4.1.65230.1.3): 16-byte UUID, the management-service enclave_id received at registration.
	OidEnclaveInstanceID = "1.3.6.1.4.1.65230.1.3"
	// OidPlatformHardwareIdentity is Platform Hardware Identity (1.3.6.1.4.1.65230.1.4): reserved for Platform Ownership Endorsements. Reserved, never emitted.
	OidPlatformHardwareIdentity = "1.3.6.1.4.1.65230.1.4"
)

// Arc 2, Platform configuration: Operator-chosen inputs of the platform.
const (
	// OidConfigMerkleRoot is Config Merkle Root (1.3.6.1.4.1.65230.2.1): 32 bytes, root over every configuration input of the platform.
	OidConfigMerkleRoot = "1.3.6.1.4.1.65230.2.1"
	// OidEgressCAHash is Egress CA Bundle Hash (1.3.6.1.4.1.65230.2.2): 32 bytes, SHA-256 of the outbound trust-anchor bundle.
	OidEgressCAHash = "1.3.6.1.4.1.65230.2.2"
	// OidAttestationServersHash is Attestation Servers Hash (1.3.6.1.4.1.65230.2.3): 32 bytes, SHA-256 of the sorted attestation server URL list.
	OidAttestationServersHash = "1.3.6.1.4.1.65230.2.3"
	// OidCombinedWorkloadsHash is Combined Workloads Hash (1.3.6.1.4.1.65230.2.4): 32 bytes, SHA-256 over the loaded workload set.
	OidCombinedWorkloadsHash = "1.3.6.1.4.1.65230.2.4"
)

// Arc 3, Platform keys and state: Key origin and authenticated state of the platform.
const (
	// OidDEKOrigin is Data Encryption Key Origin (1.3.6.1.4.1.65230.3.1): UTF-8 string, "byok:<fingerprint>" or "generated".
	OidDEKOrigin = "1.3.6.1.4.1.65230.3.1"
	// OidAuthenticatedStateRoot is Authenticated State Root (1.3.6.1.4.1.65230.3.2): 40 bytes, 32-byte Merkle root followed by a big-endian u64 version.
	OidAuthenticatedStateRoot = "1.3.6.1.4.1.65230.3.2"
)

// Arc 4, Workload identity: Which app, which code.
const (
	// OidWorkloadAppID is Workload App ID (1.3.6.1.4.1.65230.4.1): 16-byte UUID, the management app id.
	OidWorkloadAppID = "1.3.6.1.4.1.65230.4.1"
	// OidWorkloadCodeHash is Workload Code Digest (1.3.6.1.4.1.65230.4.2): 32 bytes, SHA-256 of the WASM bytecode (Mini) or of the OCI manifest (Virtual).
	OidWorkloadCodeHash = "1.3.6.1.4.1.65230.4.2"
	// OidWorkloadImageRef is Workload Image Ref (1.3.6.1.4.1.65230.4.3): UTF-8 string, image reference without digest.
	OidWorkloadImageRef = "1.3.6.1.4.1.65230.4.3"
)

// Arc 5, Workload configuration: Configuration of one workload, including the app-defined sub-arc.
const (
	// OidWorkloadConfigMerkleRoot is Workload Config Merkle Root (1.3.6.1.4.1.65230.5.1): 32 bytes.
	OidWorkloadConfigMerkleRoot = "1.3.6.1.4.1.65230.5.1"
	// OidWorkloadConfigurationHash is Workload Configuration Hash (1.3.6.1.4.1.65230.5.2): 32 bytes, runtime-stamped hash of the workload configuration.
	OidWorkloadConfigurationHash = "1.3.6.1.4.1.65230.5.2"
	// OidWorkloadReserved53 is Reserved (1.3.6.1.4.1.65230.5.3): reserved. Reserved, never emitted.
	OidWorkloadReserved53 = "1.3.6.1.4.1.65230.5.3"
	// OidWorkloadModelDigest is Model Digest (1.3.6.1.4.1.65230.5.4.5): app-defined (SDK set-attestation-extension), 32 bytes.
	OidWorkloadModelDigest = "1.3.6.1.4.1.65230.5.4.5"
	// OidWorkloadToolsDigest is Tools Digest (1.3.6.1.4.1.65230.5.4.7): app-defined (SDK set-attestation-extension), 32 bytes.
	OidWorkloadToolsDigest = "1.3.6.1.4.1.65230.5.4.7"
	// OidWorkloadPolicyDigest is Policy Digest (1.3.6.1.4.1.65230.5.4.9): app-defined (SDK set-attestation-extension), 32 bytes, SHA-256 of the workload's active service-ceiling policy document.
	OidWorkloadPolicyDigest = "1.3.6.1.4.1.65230.5.4.9"
)

// Arc 6, Workload keys and state: Key source and authenticated state of one workload.
const (
	// OidWorkloadKeySource is Workload Key Source (1.3.6.1.4.1.65230.6.1): UTF-8 string, "byok:<fingerprint>", "generated" or "vault:<path>".
	OidWorkloadKeySource = "1.3.6.1.4.1.65230.6.1"
	// OidWorkloadStateRoot is Workload State Root (1.3.6.1.4.1.65230.6.2): reserved, mirrors 3.2 for per-workload authenticated stores. Reserved, never emitted.
	OidWorkloadStateRoot = "1.3.6.1.4.1.65230.6.2"
)

// Arc 7, Trust relationships: Pinned relationships between enclaves.
const (
	// OidAttestedDependencySet is Attested Dependency Set (1.3.6.1.4.1.65230.7.1): canonical dependency-set encoding (EncodeDependencySet), written by the runtime.
	OidAttestedDependencySet = "1.3.6.1.4.1.65230.7.1"
	// OidAllowedCallers is Allowed Callers (1.3.6.1.4.1.65230.7.2): reserved, enforced from the management database today. Reserved, never emitted.
	OidAllowedCallers = "1.3.6.1.4.1.65230.7.2"
)

// Prefixes.
const (
	// OidPrivasysArcPrefix: The whole Privasys private-enterprise arc, with a trailing dot. Membership in CertInfo.CustomOids is by arc, not by allowlist.
	OidPrivasysArcPrefix = "1.3.6.1.4.1.65230."
	// OidAppExtensionArcPrefix: Sub-arc apps publish attested digests under, through the SDK set-attestation-extension call. Open-ended by design; the root 5.4 never carries a value.
	OidAppExtensionArcPrefix = "1.3.6.1.4.1.65230.5.4."
)

// Arc 8, evidence types: identifiers for the evidence bodies of the post-handshake
// attest response. Never certificate extensions.
const (
	// OidEvidenceSGXQuote is Intel SGX DCAP quote (tee "sgx").
	OidEvidenceSGXQuote = "1.3.6.1.4.1.65230.8.1"
	// OidEvidenceTDXQuote is Intel TDX DCAP quote (tee "tdx").
	OidEvidenceTDXQuote = "1.3.6.1.4.1.65230.8.2"
	// OidEvidenceSEVSNPReport is AMD SEV-SNP report (tee "sev-snp").
	OidEvidenceSEVSNPReport = "1.3.6.1.4.1.65230.8.3"
	// OidEvidenceNVIDIAGPU is NVIDIA GPU CC evidence (tee "nvidia-gpu").
	OidEvidenceNVIDIAGPU = "1.3.6.1.4.1.65230.8.4"
)

// AllOids lists every extension and prefix of the scheme with its label.
var AllOids = []OidEntry{
	{OID: OidRuntimeVersionHash, Name: "RUNTIME_VERSION_HASH", Label: "Runtime Version Hash", Category: "platform-identity", Reserved: false, AppDefined: false},
	{OID: OidImageProfile, Name: "IMAGE_PROFILE", Label: "Image Profile", Category: "platform-identity", Reserved: false, AppDefined: false},
	{OID: OidEnclaveInstanceID, Name: "ENCLAVE_INSTANCE_ID", Label: "Enclave Instance ID", Category: "platform-identity", Reserved: false, AppDefined: false},
	{OID: OidPlatformHardwareIdentity, Name: "PLATFORM_HARDWARE_IDENTITY", Label: "Platform Hardware Identity", Category: "platform-identity", Reserved: true, AppDefined: false},
	{OID: OidConfigMerkleRoot, Name: "CONFIG_MERKLE_ROOT", Label: "Config Merkle Root", Category: "platform-configuration", Reserved: false, AppDefined: false},
	{OID: OidEgressCAHash, Name: "EGRESS_CA_HASH", Label: "Egress CA Bundle Hash", Category: "platform-configuration", Reserved: false, AppDefined: false},
	{OID: OidAttestationServersHash, Name: "ATTESTATION_SERVERS_HASH", Label: "Attestation Servers Hash", Category: "platform-configuration", Reserved: false, AppDefined: false},
	{OID: OidCombinedWorkloadsHash, Name: "COMBINED_WORKLOADS_HASH", Label: "Combined Workloads Hash", Category: "platform-configuration", Reserved: false, AppDefined: false},
	{OID: OidDEKOrigin, Name: "DEK_ORIGIN", Label: "Data Encryption Key Origin", Category: "platform-keys-state", Reserved: false, AppDefined: false},
	{OID: OidAuthenticatedStateRoot, Name: "AUTHENTICATED_STATE_ROOT", Label: "Authenticated State Root", Category: "platform-keys-state", Reserved: false, AppDefined: false},
	{OID: OidWorkloadAppID, Name: "WORKLOAD_APP_ID", Label: "Workload App ID", Category: "workload-identity", Reserved: false, AppDefined: false},
	{OID: OidWorkloadCodeHash, Name: "WORKLOAD_CODE_HASH", Label: "Workload Code Digest", Category: "workload-identity", Reserved: false, AppDefined: false},
	{OID: OidWorkloadImageRef, Name: "WORKLOAD_IMAGE_REF", Label: "Workload Image Ref", Category: "workload-identity", Reserved: false, AppDefined: false},
	{OID: OidWorkloadConfigMerkleRoot, Name: "WORKLOAD_CONFIG_MERKLE_ROOT", Label: "Workload Config Merkle Root", Category: "workload-configuration", Reserved: false, AppDefined: false},
	{OID: OidWorkloadConfigurationHash, Name: "WORKLOAD_CONFIGURATION_HASH", Label: "Workload Configuration Hash", Category: "workload-configuration", Reserved: false, AppDefined: false},
	{OID: OidWorkloadReserved53, Name: "WORKLOAD_RESERVED_5_3", Label: "Reserved", Category: "workload-configuration", Reserved: true, AppDefined: false},
	{OID: OidWorkloadModelDigest, Name: "WORKLOAD_MODEL_DIGEST", Label: "Model Digest", Category: "workload-configuration", Reserved: false, AppDefined: true},
	{OID: OidWorkloadToolsDigest, Name: "WORKLOAD_TOOLS_DIGEST", Label: "Tools Digest", Category: "workload-configuration", Reserved: false, AppDefined: true},
	{OID: OidWorkloadPolicyDigest, Name: "WORKLOAD_POLICY_DIGEST", Label: "Policy Digest", Category: "workload-configuration", Reserved: false, AppDefined: true},
	{OID: OidWorkloadKeySource, Name: "WORKLOAD_KEY_SOURCE", Label: "Workload Key Source", Category: "workload-keys-state", Reserved: false, AppDefined: false},
	{OID: OidWorkloadStateRoot, Name: "WORKLOAD_STATE_ROOT", Label: "Workload State Root", Category: "workload-keys-state", Reserved: true, AppDefined: false},
	{OID: OidAttestedDependencySet, Name: "ATTESTED_DEPENDENCY_SET", Label: "Attested Dependency Set", Category: "trust", Reserved: false, AppDefined: false},
	{OID: OidAllowedCallers, Name: "ALLOWED_CALLERS", Label: "Allowed Callers", Category: "trust", Reserved: true, AppDefined: false},
}

// OidLabel returns a human-readable label for a known OID, or "Unknown".
func OidLabel(oid string) string {
	switch oid {
	case "1.2.840.113741.1.13.1.0":
		return "SGX Quote"
	case "1.2.840.113741.1.5.5.1.6":
		return "TDX Quote"
	case "1.3.6.1.4.1.65230.1.1":
		return "Runtime Version Hash"
	case "1.3.6.1.4.1.65230.1.2":
		return "Image Profile"
	case "1.3.6.1.4.1.65230.1.3":
		return "Enclave Instance ID"
	case "1.3.6.1.4.1.65230.1.4":
		return "Platform Hardware Identity"
	case "1.3.6.1.4.1.65230.2.1":
		return "Config Merkle Root"
	case "1.3.6.1.4.1.65230.2.2":
		return "Egress CA Bundle Hash"
	case "1.3.6.1.4.1.65230.2.3":
		return "Attestation Servers Hash"
	case "1.3.6.1.4.1.65230.2.4":
		return "Combined Workloads Hash"
	case "1.3.6.1.4.1.65230.3.1":
		return "Data Encryption Key Origin"
	case "1.3.6.1.4.1.65230.3.2":
		return "Authenticated State Root"
	case "1.3.6.1.4.1.65230.4.1":
		return "Workload App ID"
	case "1.3.6.1.4.1.65230.4.2":
		return "Workload Code Digest"
	case "1.3.6.1.4.1.65230.4.3":
		return "Workload Image Ref"
	case "1.3.6.1.4.1.65230.5.1":
		return "Workload Config Merkle Root"
	case "1.3.6.1.4.1.65230.5.2":
		return "Workload Configuration Hash"
	case "1.3.6.1.4.1.65230.5.3":
		return "Reserved"
	case "1.3.6.1.4.1.65230.5.4.5":
		return "Model Digest"
	case "1.3.6.1.4.1.65230.5.4.7":
		return "Tools Digest"
	case "1.3.6.1.4.1.65230.5.4.9":
		return "Policy Digest"
	case "1.3.6.1.4.1.65230.6.1":
		return "Workload Key Source"
	case "1.3.6.1.4.1.65230.6.2":
		return "Workload State Root"
	case "1.3.6.1.4.1.65230.7.1":
		return "Attested Dependency Set"
	case "1.3.6.1.4.1.65230.7.2":
		return "Allowed Callers"
	case "1.3.6.1.4.1.65230.8.1":
		return "Intel SGX DCAP quote"
	case "1.3.6.1.4.1.65230.8.2":
		return "Intel TDX DCAP quote"
	case "1.3.6.1.4.1.65230.8.3":
		return "AMD SEV-SNP report"
	case "1.3.6.1.4.1.65230.8.4":
		return "NVIDIA GPU CC evidence"
	}
	if len(oid) > len(OidAppExtensionArcPrefix) && oid[:len(OidAppExtensionArcPrefix)] == OidAppExtensionArcPrefix {
		return "App-defined extension " + oid[len(OidAppExtensionArcPrefix):]
	}
	return "Unknown"
}
